/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * A whole, non-negative count of bars: a period, lag, or window length.
 *
 * This is a plain `number` to TypeScript. It is named because the binding
 * validates it at the boundary rather than coercing it: a fractional,
 * negative, or non-finite value is refused with a message naming what was
 * passed, instead of arriving at the indicator as a plausible-looking period.
 * The domain rules (a period of zero, the maximum window length) still live in
 * the Rust constructor.
 */
export type Count = number

/**
 * A numeric input series: a `Float64Array` is read in place without a copy,
 * any other array of numbers is converted element by element. A typed array of
 * another element type is refused rather than reinterpreted.
 */
export type Series = Float64Array | Array<number>

/**
 * A caller-owned `Float64Array` a `batchInto` / `batchFastInto` call writes
 * its result into. It must be exactly as long as the result, must not share
 * memory with an input, and must not be backed by a `SharedArrayBuffer`;
 * anything else is refused.
 */
export type OutSeries = Float64Array
