/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('fs')
let nativeBinding = null
// Which artifact actually loaded. The WASI fallback chain overwrites it with
// the flavor it resolved; the late native retry below leaves it alone because
// it only runs while no WASI candidate has been loaded.
let __napiLoadedBindingTarget = 'native'
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (process.report && typeof process.report.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      const overrideBinding = require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH)
      // The override may be a generated WASI loader, which already reports its
      // own flavor. Adopt it: `module.exports` aliases this object, so claiming
      // 'native' would both misreport the artifact and overwrite the loader's
      // marker through the alias.
      __napiLoadedBindingTarget =
        overrideBinding && typeof overrideBinding.__napiBindingTarget === 'string'
          ? overrideBinding.__napiBindingTarget
          : 'native'
      return overrideBinding
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./wickra.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('wickra-android-arm64')
        const bindingPackageVersion = require('wickra-android-arm64/package.json').version
        if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./wickra.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('wickra-android-arm-eabi')
        const bindingPackageVersion = require('wickra-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if ((process.config && process.config.variables && process.config.variables.shlib_suffix === 'dll.a') || (process.config && process.config.variables && process.config.variables.node_target_type === 'shared_library')) {
        try {
          return require('./wickra.win32-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('wickra-win32-x64-gnu')
          const bindingPackageVersion = require('wickra-win32-x64-gnu/package.json').version
          if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./wickra.win32-x64-msvc.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('wickra-win32-x64-msvc')
          const bindingPackageVersion = require('wickra-win32-x64-msvc/package.json').version
          if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./wickra.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('wickra-win32-ia32-msvc')
        const bindingPackageVersion = require('wickra-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./wickra.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('wickra-win32-arm64-msvc')
        const bindingPackageVersion = require('wickra-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./wickra.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('wickra-darwin-universal')
      const bindingPackageVersion = require('wickra-darwin-universal/package.json').version
      if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./wickra.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('wickra-darwin-x64')
        const bindingPackageVersion = require('wickra-darwin-x64/package.json').version
        if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./wickra.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('wickra-darwin-arm64')
        const bindingPackageVersion = require('wickra-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./wickra.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('wickra-freebsd-x64')
        const bindingPackageVersion = require('wickra-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./wickra.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('wickra-freebsd-arm64')
        const bindingPackageVersion = require('wickra-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./wickra.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('wickra-linux-x64-musl')
          const bindingPackageVersion = require('wickra-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./wickra.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('wickra-linux-x64-gnu')
          const bindingPackageVersion = require('wickra-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./wickra.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('wickra-linux-arm64-musl')
          const bindingPackageVersion = require('wickra-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./wickra.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('wickra-linux-arm64-gnu')
          const bindingPackageVersion = require('wickra-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./wickra.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('wickra-linux-arm-musleabihf')
          const bindingPackageVersion = require('wickra-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./wickra.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('wickra-linux-arm-gnueabihf')
          const bindingPackageVersion = require('wickra-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./wickra.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('wickra-linux-loong64-musl')
          const bindingPackageVersion = require('wickra-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./wickra.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('wickra-linux-loong64-gnu')
          const bindingPackageVersion = require('wickra-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./wickra.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('wickra-linux-riscv64-musl')
          const bindingPackageVersion = require('wickra-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./wickra.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('wickra-linux-riscv64-gnu')
          const bindingPackageVersion = require('wickra-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./wickra.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('wickra-linux-ppc64-gnu')
        const bindingPackageVersion = require('wickra-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./wickra.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('wickra-linux-s390x-gnu')
        const bindingPackageVersion = require('wickra-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./wickra.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('wickra-openharmony-arm64')
        const bindingPackageVersion = require('wickra-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./wickra.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('wickra-openharmony-x64')
        const bindingPackageVersion = require('wickra-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./wickra.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('wickra-openharmony-arm')
        const bindingPackageVersion = require('wickra-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '1.0.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

function createLoadErrorChain(errors) {
  return errors.reduce((previous, current) => {
    let message
    try {
      message =
        current && typeof current.message === 'string'
          ? current.message
          : String(current)
    } catch {
      message = 'Unknown error'
    }
    const error = new Error(message)
    error.cause = previous
    return error
  }, null)
}

// NAPI_RS_FORCE_WASI is a tri-state flag:
//   unset / any other value → native binding preferred, WASI is only a fallback
//   'true'                   → prefer WASI, but retain native as a lazy fallback
//   'error'                  → require WASI without initializing a native fallback
// Treating any non-empty string as truthy (the historical behavior) meant
// NAPI_RS_FORCE_WASI=false, NAPI_RS_FORCE_WASI=0, etc. inadvertently triggered
// the WASI path, causing ENOENT for packages shipped without a .wasi.cjs file.
//
// NAPI_RS_WASI_FLAVOR selects one exact generated flavor and implies strict
// WASI loading. It never crosses into another flavor or falls back to native.
const __napiWasiFlavors = ['wasm32-wasi']
const __napiWasiFlavor = process.env.NAPI_RS_WASI_FLAVOR
const __napiWasiFlavorRequested =
  typeof __napiWasiFlavor === 'string' && __napiWasiFlavor.length > 0
if (
  __napiWasiFlavorRequested &&
  __napiWasiFlavors.indexOf(__napiWasiFlavor) === -1
) {
  throw new Error(
    'Unsupported WASI flavor "' +
      __napiWasiFlavor +
      '". Available flavors: ' +
      __napiWasiFlavors.join(', '),
  )
}
const forceWasiError = process.env.NAPI_RS_FORCE_WASI === 'error'
const forceWasi =
  process.env.NAPI_RS_FORCE_WASI === 'true' ||
  forceWasiError ||
  __napiWasiFlavorRequested

if (!forceWasi) {
  nativeBinding = requireNative()
}

if (!nativeBinding || forceWasi) {
  let wasiBinding = null
  let wasiBindingLoaded = false
  const wasiBindingErrors = []
  const __napiWasiResolveCandidate = (specifier, isPackage, localArtifacts) => {
    try {
      require.resolve(specifier)
    } catch (resolveError) {
      if (!resolveError || resolveError.code !== 'MODULE_NOT_FOUND') {
        throw resolveError
      }
      if (isPackage) {
        try {
          require.resolve(specifier + '/package.json')
        } catch (packageError) {
          if (packageError && packageError.code === 'MODULE_NOT_FOUND') {
            return resolveError
          }
          // An exports restriction proves the package exists even when its
          // package.json is not public. Preserve the root resolution failure.
          throw resolveError
        }
        // The package exists but its main/export target is broken.
        throw resolveError
      }
      return resolveError
    }
    if (localArtifacts) {
      let artifactError = null
      for (let i = 0; i < localArtifacts.length; i++) {
        try {
          require.resolve(localArtifacts[i])
          return null
        } catch (resolveError) {
          if (!resolveError || resolveError.code !== 'MODULE_NOT_FOUND') {
            throw resolveError
          }
          artifactError = resolveError
        }
      }
      return artifactError
    }
    return null
  }
  if (!wasiBindingLoaded && (!__napiWasiFlavorRequested || __napiWasiFlavor === 'wasm32-wasi')) {
    let candidateError = null
    let candidateFailed = false
    try {
      candidateError = __napiWasiResolveCandidate('./wickra.wasi.cjs', false, ['./wickra.wasm32-wasi.debug.wasm', './wickra.wasm32-wasi.wasm'])
      candidateFailed = candidateError !== null
      if (!candidateFailed) {
        wasiBinding = require('./wickra.wasi.cjs')
        nativeBinding = wasiBinding
        __napiLoadedBindingTarget = 'wasm32-wasi'
        wasiBindingLoaded = true
      }
    } catch (err) {
      candidateError = err
      candidateFailed = true
    }
    if (candidateFailed) {
      wasiBindingErrors.push(candidateError)
      loadErrors.push(candidateError)
    }
  }
  if (!wasiBindingLoaded && (!__napiWasiFlavorRequested || __napiWasiFlavor === 'wasm32-wasi')) {
    let candidateError = null
    let candidateFailed = false
    try {
      candidateError = __napiWasiResolveCandidate('wickra-wasm32-wasi', true, undefined)
      candidateFailed = candidateError !== null
      if (!candidateFailed) {
        if (process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          const bindingPackageVersion = require('wickra-wasm32-wasi/package.json').version
          if (bindingPackageVersion !== '1.0.5') {
            throw new Error(`WASI binding package version mismatch, expected 1.0.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
        }
        wasiBinding = require('wickra-wasm32-wasi')
        nativeBinding = wasiBinding
        __napiLoadedBindingTarget = 'wasm32-wasi'
        wasiBindingLoaded = true
      }
    } catch (err) {
      candidateError = err
      candidateFailed = true
    }
    if (candidateFailed) {
      wasiBindingErrors.push(candidateError)
      loadErrors.push(candidateError)
    }
  }
  if (
    !wasiBindingLoaded &&
    forceWasi &&
    !forceWasiError &&
    !__napiWasiFlavorRequested
  ) {
    nativeBinding = requireNative()
  }
  if ((forceWasiError || __napiWasiFlavorRequested) && !wasiBindingLoaded) {
    const error = new Error(
      __napiWasiFlavorRequested
        ? 'WASI binding for flavor "' + __napiWasiFlavor + '" not found'
        : 'WASI binding not found and NAPI_RS_FORCE_WASI is set to error',
    )
    error.cause = createLoadErrorChain(wasiBindingErrors)
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    const error = new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
    )
    // assign instead of the `new Error(message, { cause })` options form,
    // which Node < 16.9 silently ignores
    error.cause = createLoadErrorChain(loadErrors)
    throw error
  }
  throw new Error(`Failed to load native binding`)
}

function __napiStampBindingTarget(exportsObject, target) {
  if (
    Object.prototype.hasOwnProperty.call(exportsObject, '__napiBindingTarget')
  ) {
    if (exportsObject.__napiBindingTarget === target) {
      // Already ours: the root entry aliases the object it loaded, so a WASI
      // fallback candidate — or a `NAPI_RS_NATIVE_LIBRARY_PATH` override that
      // is a generated loader — arrives already stamped with this same value.
      return target
    }
    const error = new Error(
      '`__napiBindingTarget` is reserved by the generated binding loader, but the loaded binding already exports it. Rename the export, e.g. #[napi(js_name = "...")].',
    )
    error.code = 'ERR_NAPI_BINDING_TARGET_CONFLICT'
    throw error
  }
  if (!Object.isExtensible(exportsObject)) {
    // A `#[napi(module_exports)]` hook may seal or freeze this object
    // (`Object::seal` / `Object::freeze`). Reporting the artifact is metadata,
    // never a reason to fail an otherwise successful load, so the stamp is
    // skipped. What a consumer still sees then follows the entry point: the
    // browser and deferred loaders declare `__napiBindingTarget` at module
    // level and go on reporting it, while the CommonJS entries hand back this
    // very object as `module.exports`, so there the value is absent.
    return target
  }
  try {
    // [[Define]], not [[Set]]: an ordinary assignment walks the prototype
    // chain, so an inherited accessor could swallow the value or throw and
    // fail an otherwise successful load. The descriptor is what a successful
    // assignment would have produced.
    Object.defineProperty(exportsObject, '__napiBindingTarget', {
      configurable: true,
      enumerable: true,
      value: target,
      writable: true,
    })
  } catch {
    // Same rule as the non-extensible skip above: reporting the artifact is
    // metadata, never a reason to fail an otherwise successful load. An exotic
    // object (a Proxy whose defineProperty trap refuses) is skipped, not
    // thrown over.
  }
  // The CommonJS loaders assign this return value so `cjs-module-lexer` — and
  // therefore Node's CJS -> ESM named export detection — can see
  // `__napiBindingTarget` statically.
  return target
}
// Stamp before the alias, not after. The guard only reads `nativeBinding`
// (`hasOwnProperty` plus a comparison), which is safe against any addon
// accessor; an assignment is not, because a `#[napi(module_exports)]` hook can
// expose a getter reporting this very value and a setter that throws. So the
// assignment lands on the loader's own `module.exports`, still the original
// object here, and the alias below replaces it.
//
// The assignment is what keeps the marker a statically visible CommonJS export:
// `cjs-module-lexer` is Node's CJS -> ESM named export detection, it cannot see
// a bare call, and the later `module.exports = nativeBinding` does not undo the
// detection. The assignment itself always succeeds — its target is this
// loader's own, still extensible `module.exports` — and the alias below then
// discards the value it wrote. What a consumer reads is whatever the guard put
// on `nativeBinding`, so on a frozen binding, where the guard skips, the
// linked import resolves to `undefined`.
module.exports.__napiBindingTarget = __napiStampBindingTarget(nativeBinding, __napiLoadedBindingTarget)
module.exports = nativeBinding
module.exports.AbandonedBaby = nativeBinding.AbandonedBaby
module.exports.Abcd = nativeBinding.Abcd
module.exports.AbsoluteBreadthIndex = nativeBinding.AbsoluteBreadthIndex
module.exports.AccelerationBands = nativeBinding.AccelerationBands
module.exports.AcceleratorOscillator = nativeBinding.AcceleratorOscillator
module.exports.ADAPTIVECCI = nativeBinding.ADAPTIVECCI
module.exports.AdaptiveCycle = nativeBinding.AdaptiveCycle
module.exports.AdaptiveLaguerre = nativeBinding.AdaptiveLaguerre
module.exports.ADAPTIVERSI = nativeBinding.ADAPTIVERSI
module.exports.ADL = nativeBinding.ADL
module.exports.ADOSC = nativeBinding.ADOSC
module.exports.AdvanceBlock = nativeBinding.AdvanceBlock
module.exports.AdvanceDecline = nativeBinding.AdvanceDecline
module.exports.AdvanceDeclineRatio = nativeBinding.AdvanceDeclineRatio
module.exports.AdVolumeLine = nativeBinding.AdVolumeLine
module.exports.ADX = nativeBinding.ADX
module.exports.ADXR = nativeBinding.ADXR
module.exports.Alligator = nativeBinding.Alligator
module.exports.ALMA = nativeBinding.ALMA
module.exports.Alpha = nativeBinding.Alpha
module.exports.AmihudIlliquidity = nativeBinding.AmihudIlliquidity
module.exports.AnchoredRSI = nativeBinding.AnchoredRSI
module.exports.AnchoredVWAP = nativeBinding.AnchoredVWAP
module.exports.AndrewsPitchfork = nativeBinding.AndrewsPitchfork
module.exports.APO = nativeBinding.APO
module.exports.Aroon = nativeBinding.Aroon
module.exports.AroonOscillator = nativeBinding.AroonOscillator
module.exports.ATR = nativeBinding.ATR
module.exports.AtrBands = nativeBinding.AtrBands
module.exports.AtrRatchet = nativeBinding.AtrRatchet
module.exports.AtrTrailingStop = nativeBinding.AtrTrailingStop
module.exports.Autocorrelation = nativeBinding.Autocorrelation
module.exports.AUTOCORRPGRAM = nativeBinding.AUTOCORRPGRAM
module.exports.AutoFib = nativeBinding.AutoFib
module.exports.AverageDailyRange = nativeBinding.AverageDailyRange
module.exports.AverageDrawdown = nativeBinding.AverageDrawdown
module.exports.AVGPRICE = nativeBinding.AVGPRICE
module.exports.AwesomeOscillator = nativeBinding.AwesomeOscillator
module.exports.AwesomeOscillatorHistogram = nativeBinding.AwesomeOscillatorHistogram
module.exports.BalanceOfPower = nativeBinding.BalanceOfPower
module.exports.BANDPASS = nativeBinding.BANDPASS
module.exports.Bat = nativeBinding.Bat
module.exports.BeltHold = nativeBinding.BeltHold
module.exports.Beta = nativeBinding.Beta
module.exports.BetaNeutralSpread = nativeBinding.BetaNeutralSpread
module.exports.BetterVolume = nativeBinding.BetterVolume
module.exports.BinanceFeed = nativeBinding.BinanceFeed
module.exports.BipowerVariation = nativeBinding.BipowerVariation
module.exports.BodySizePct = nativeBinding.BodySizePct
module.exports.BollingerBands = nativeBinding.BollingerBands
module.exports.BollingerBandwidth = nativeBinding.BollingerBandwidth
module.exports.BomarBands = nativeBinding.BomarBands
module.exports.BreadthThrust = nativeBinding.BreadthThrust
module.exports.Breakaway = nativeBinding.Breakaway
module.exports.BullishPercentIndex = nativeBinding.BullishPercentIndex
module.exports.BurkeRatio = nativeBinding.BurkeRatio
module.exports.Butterfly = nativeBinding.Butterfly
module.exports.CalendarSpread = nativeBinding.CalendarSpread
module.exports.CalmarRatio = nativeBinding.CalmarRatio
module.exports.Camarilla = nativeBinding.Camarilla
module.exports.CandleReader = nativeBinding.CandleReader
module.exports.CandleVolume = nativeBinding.CandleVolume
module.exports.CCI = nativeBinding.CCI
module.exports.CenterOfGravity = nativeBinding.CenterOfGravity
module.exports.CentralPivotRange = nativeBinding.CentralPivotRange
module.exports.CFO = nativeBinding.CFO
module.exports.ChaikinMoneyFlow = nativeBinding.ChaikinMoneyFlow
module.exports.ChaikinOscillator = nativeBinding.ChaikinOscillator
module.exports.ChaikinVolatility = nativeBinding.ChaikinVolatility
module.exports.ChandeKrollStop = nativeBinding.ChandeKrollStop
module.exports.ChandelierExit = nativeBinding.ChandelierExit
module.exports.ChoppinessIndex = nativeBinding.ChoppinessIndex
module.exports.ClassicPivots = nativeBinding.ClassicPivots
module.exports.CloseVsOpen = nativeBinding.CloseVsOpen
module.exports.ClosingMarubozu = nativeBinding.ClosingMarubozu
module.exports.CMO = nativeBinding.CMO
module.exports.CoefficientOfVariation = nativeBinding.CoefficientOfVariation
module.exports.Cointegration = nativeBinding.Cointegration
module.exports.CommonSenseRatio = nativeBinding.CommonSenseRatio
module.exports.CompositeProfile = nativeBinding.CompositeProfile
module.exports.ConcealingBabySwallow = nativeBinding.ConcealingBabySwallow
module.exports.ConditionalValueAtRisk = nativeBinding.ConditionalValueAtRisk
module.exports.ConnorsRSI = nativeBinding.ConnorsRSI
module.exports.Coppock = nativeBinding.Coppock
module.exports.Counterattack = nativeBinding.Counterattack
module.exports.Crab = nativeBinding.Crab
module.exports.CTI = nativeBinding.CTI
module.exports.CumulativeVolumeDelta = nativeBinding.CumulativeVolumeDelta
module.exports.CumulativeVolumeIndex = nativeBinding.CumulativeVolumeIndex
module.exports.CupAndHandle = nativeBinding.CupAndHandle
module.exports.CyberneticCycle = nativeBinding.CyberneticCycle
module.exports.Cypher = nativeBinding.Cypher
module.exports.DayOfWeekProfile = nativeBinding.DayOfWeekProfile
module.exports.Decycler = nativeBinding.Decycler
module.exports.DecyclerOscillator = nativeBinding.DecyclerOscillator
module.exports.DEMA = nativeBinding.DEMA
module.exports.DemandIndex = nativeBinding.DemandIndex
module.exports.DemarkPivots = nativeBinding.DemarkPivots
module.exports.DepthSlope = nativeBinding.DepthSlope
module.exports.DerivativeOscillator = nativeBinding.DerivativeOscillator
module.exports.DetrendedStdDev = nativeBinding.DetrendedStdDev
module.exports.DisparityIndex = nativeBinding.DisparityIndex
module.exports.DistanceSsd = nativeBinding.DistanceSsd
module.exports.Doji = nativeBinding.Doji
module.exports.DojiStar = nativeBinding.DojiStar
module.exports.DollarBars = nativeBinding.DollarBars
module.exports.Donchian = nativeBinding.Donchian
module.exports.DonchianStop = nativeBinding.DonchianStop
module.exports.DoubleBollinger = nativeBinding.DoubleBollinger
module.exports.DoubleTopBottom = nativeBinding.DoubleTopBottom
module.exports.DownsideGapThreeMethods = nativeBinding.DownsideGapThreeMethods
module.exports.DPO = nativeBinding.DPO
module.exports.DragonflyDoji = nativeBinding.DragonflyDoji
module.exports.DrawdownDuration = nativeBinding.DrawdownDuration
module.exports.DumplingTop = nativeBinding.DumplingTop
module.exports.DX = nativeBinding.DX
module.exports.DynamicMomentumIndex = nativeBinding.DynamicMomentumIndex
module.exports.EaseOfMovement = nativeBinding.EaseOfMovement
module.exports.EffectiveSpread = nativeBinding.EffectiveSpread
module.exports.EhlersStochastic = nativeBinding.EhlersStochastic
module.exports.EHMA = nativeBinding.EHMA
module.exports.ElderImpulse = nativeBinding.ElderImpulse
module.exports.ElderRay = nativeBinding.ElderRay
module.exports.ElderSafeZone = nativeBinding.ElderSafeZone
module.exports.EMA = nativeBinding.EMA
module.exports.EmpiricalModeDecomposition = nativeBinding.EmpiricalModeDecomposition
module.exports.Engulfing = nativeBinding.Engulfing
module.exports.Equivolume = nativeBinding.Equivolume
module.exports.EstimatedLeverageRatio = nativeBinding.EstimatedLeverageRatio
module.exports.EVENBETTERSINE = nativeBinding.EVENBETTERSINE
module.exports.EveningDojiStar = nativeBinding.EveningDojiStar
module.exports.EVWMA = nativeBinding.EVWMA
module.exports.EwmaVolatility = nativeBinding.EwmaVolatility
module.exports.Expectancy = nativeBinding.Expectancy
module.exports.FallingThreeMethods = nativeBinding.FallingThreeMethods
module.exports.FAMA = nativeBinding.FAMA
module.exports.FibArcs = nativeBinding.FibArcs
module.exports.FibChannel = nativeBinding.FibChannel
module.exports.FibConfluence = nativeBinding.FibConfluence
module.exports.FibExtension = nativeBinding.FibExtension
module.exports.FibFan = nativeBinding.FibFan
module.exports.FibonacciPivots = nativeBinding.FibonacciPivots
module.exports.FibProjection = nativeBinding.FibProjection
module.exports.FibRetracement = nativeBinding.FibRetracement
module.exports.FibTimeZones = nativeBinding.FibTimeZones
module.exports.FisherRSI = nativeBinding.FisherRSI
module.exports.FisherTransform = nativeBinding.FisherTransform
module.exports.FlagPennant = nativeBinding.FlagPennant
module.exports.Footprint = nativeBinding.Footprint
module.exports.ForceIndex = nativeBinding.ForceIndex
module.exports.FractalChaosBands = nativeBinding.FractalChaosBands
module.exports.FRAMA = nativeBinding.FRAMA
module.exports.FryPanBottom = nativeBinding.FryPanBottom
module.exports.FundingBasis = nativeBinding.FundingBasis
module.exports.FundingImpliedApr = nativeBinding.FundingImpliedApr
module.exports.FundingRate = nativeBinding.FundingRate
module.exports.FundingRateMean = nativeBinding.FundingRateMean
module.exports.FundingRateZScore = nativeBinding.FundingRateZScore
module.exports.GainLossRatio = nativeBinding.GainLossRatio
module.exports.GainToPainRatio = nativeBinding.GainToPainRatio
module.exports.GapSideBySideWhite = nativeBinding.GapSideBySideWhite
module.exports.Garch11 = nativeBinding.Garch11
module.exports.GarmanKlassVolatility = nativeBinding.GarmanKlassVolatility
module.exports.Gartley = nativeBinding.Gartley
module.exports.GatorOscillator = nativeBinding.GatorOscillator
module.exports.GD = nativeBinding.GD
module.exports.GMA = nativeBinding.GMA
module.exports.GoldenPocket = nativeBinding.GoldenPocket
module.exports.GrangerCausality = nativeBinding.GrangerCausality
module.exports.GravestoneDoji = nativeBinding.GravestoneDoji
module.exports.Hammer = nativeBinding.Hammer
module.exports.HangingMan = nativeBinding.HangingMan
module.exports.Harami = nativeBinding.Harami
module.exports.HaramiCross = nativeBinding.HaramiCross
module.exports.HasbrouckInformationShare = nativeBinding.HasbrouckInformationShare
module.exports.HeadAndShoulders = nativeBinding.HeadAndShoulders
module.exports.HeikinAshi = nativeBinding.HeikinAshi
module.exports.HeikinAshiOscillator = nativeBinding.HeikinAshiOscillator
module.exports.HighLowIndex = nativeBinding.HighLowIndex
module.exports.HighLowRange = nativeBinding.HighLowRange
module.exports.HighLowVolumeNodes = nativeBinding.HighLowVolumeNodes
module.exports.HIGHPASS = nativeBinding.HIGHPASS
module.exports.HighWave = nativeBinding.HighWave
module.exports.Hikkake = nativeBinding.Hikkake
module.exports.HikkakeModified = nativeBinding.HikkakeModified
module.exports.HilbertDominantCycle = nativeBinding.HilbertDominantCycle
module.exports.HiLoActivator = nativeBinding.HiLoActivator
module.exports.HistoricalVolatility = nativeBinding.HistoricalVolatility
module.exports.HMA = nativeBinding.HMA
module.exports.HoltWinters = nativeBinding.HoltWinters
module.exports.HomingPigeon = nativeBinding.HomingPigeon
module.exports.HT_DCPHASE = nativeBinding.HT_DCPHASE
module.exports.HT_PHASOR = nativeBinding.HT_PHASOR
module.exports.HT_TRENDMODE = nativeBinding.HT_TRENDMODE
module.exports.HurstChannel = nativeBinding.HurstChannel
module.exports.HurstExponent = nativeBinding.HurstExponent
module.exports.Ichimoku = nativeBinding.Ichimoku
module.exports.IdenticalThreeCrows = nativeBinding.IdenticalThreeCrows
module.exports.ImbalanceBars = nativeBinding.ImbalanceBars
module.exports.IMI = nativeBinding.IMI
module.exports.Inertia = nativeBinding.Inertia
module.exports.InformationRatio = nativeBinding.InformationRatio
module.exports.InitialBalance = nativeBinding.InitialBalance
module.exports.InNeck = nativeBinding.InNeck
module.exports.InstantaneousTrendline = nativeBinding.InstantaneousTrendline
module.exports.IntradayIntensity = nativeBinding.IntradayIntensity
module.exports.IntradayVolatilityProfile = nativeBinding.IntradayVolatilityProfile
module.exports.InverseFisherTransform = nativeBinding.InverseFisherTransform
module.exports.InvertedHammer = nativeBinding.InvertedHammer
module.exports.JARQUEBERA = nativeBinding.JARQUEBERA
module.exports.JMA = nativeBinding.JMA
module.exports.JumpIndicator = nativeBinding.JumpIndicator
module.exports.KagiBars = nativeBinding.KagiBars
module.exports.KalmanHedgeRatio = nativeBinding.KalmanHedgeRatio
module.exports.KAMA = nativeBinding.KAMA
module.exports.KaseDevStop = nativeBinding.KaseDevStop
module.exports.KasePermissionStochastic = nativeBinding.KasePermissionStochastic
module.exports.KellyCriterion = nativeBinding.KellyCriterion
module.exports.Keltner = nativeBinding.Keltner
module.exports.KendallTau = nativeBinding.KendallTau
module.exports.Kicking = nativeBinding.Kicking
module.exports.KickingByLength = nativeBinding.KickingByLength
module.exports.KRatio = nativeBinding.KRatio
module.exports.KST = nativeBinding.KST
module.exports.Kurtosis = nativeBinding.Kurtosis
module.exports.KVO = nativeBinding.KVO
module.exports.KylesLambda = nativeBinding.KylesLambda
module.exports.LadderBottom = nativeBinding.LadderBottom
module.exports.LaguerreRSI = nativeBinding.LaguerreRSI
module.exports.LeadLagCrossCorrelation = nativeBinding.LeadLagCrossCorrelation
module.exports.LINEARREG_INTERCEPT = nativeBinding.LINEARREG_INTERCEPT
module.exports.LinearRegression = nativeBinding.LinearRegression
module.exports.LinRegAngle = nativeBinding.LinRegAngle
module.exports.LinRegChannel = nativeBinding.LinRegChannel
module.exports.LinRegSlope = nativeBinding.LinRegSlope
module.exports.LiquidationFeatures = nativeBinding.LiquidationFeatures
module.exports.LogReturn = nativeBinding.LogReturn
module.exports.LongLeggedDoji = nativeBinding.LongLeggedDoji
module.exports.LongLine = nativeBinding.LongLine
module.exports.LongShortRatio = nativeBinding.LongShortRatio
module.exports.M2Measure = nativeBinding.M2Measure
module.exports.MACD = nativeBinding.MACD
module.exports.MACDEXT = nativeBinding.MACDEXT
module.exports.MACDFIX = nativeBinding.MACDFIX
module.exports.MacdHistogram = nativeBinding.MacdHistogram
module.exports.MaEnvelope = nativeBinding.MaEnvelope
module.exports.MAMA = nativeBinding.MAMA
module.exports.MarketFacilitationIndex = nativeBinding.MarketFacilitationIndex
module.exports.MartinRatio = nativeBinding.MartinRatio
module.exports.Marubozu = nativeBinding.Marubozu
module.exports.MassIndex = nativeBinding.MassIndex
module.exports.MatchingLow = nativeBinding.MatchingLow
module.exports.MatHold = nativeBinding.MatHold
module.exports.MaxDrawdown = nativeBinding.MaxDrawdown
module.exports.McClellanOscillator = nativeBinding.McClellanOscillator
module.exports.McClellanSummationIndex = nativeBinding.McClellanSummationIndex
module.exports.McGinleyDynamic = nativeBinding.McGinleyDynamic
module.exports.MedianAbsoluteDeviation = nativeBinding.MedianAbsoluteDeviation
module.exports.MedianChannel = nativeBinding.MedianChannel
module.exports.MedianMA = nativeBinding.MedianMA
module.exports.MedianPrice = nativeBinding.MedianPrice
module.exports.MFI = nativeBinding.MFI
module.exports.Microprice = nativeBinding.Microprice
module.exports.MIDPOINT = nativeBinding.MIDPOINT
module.exports.MIDPRICE = nativeBinding.MIDPRICE
module.exports.MINUS_DI = nativeBinding.MINUS_DI
module.exports.MINUS_DM = nativeBinding.MINUS_DM
module.exports.ModifiedMaStop = nativeBinding.ModifiedMaStop
module.exports.MOM = nativeBinding.MOM
module.exports.MorningDojiStar = nativeBinding.MorningDojiStar
module.exports.MorningEveningStar = nativeBinding.MorningEveningStar
module.exports.MurreyMathLines = nativeBinding.MurreyMathLines
module.exports.NakedPoc = nativeBinding.NakedPoc
module.exports.NATR = nativeBinding.NATR
module.exports.NewHighsNewLows = nativeBinding.NewHighsNewLows
module.exports.NewPriceLines = nativeBinding.NewPriceLines
module.exports.Nrtr = nativeBinding.Nrtr
module.exports.NVI = nativeBinding.NVI
module.exports.OBV = nativeBinding.OBV
module.exports.OIPriceDivergence = nativeBinding.OIPriceDivergence
module.exports.OiToVolumeRatio = nativeBinding.OiToVolumeRatio
module.exports.OIWeighted = nativeBinding.OIWeighted
module.exports.OmegaRatio = nativeBinding.OmegaRatio
module.exports.OnNeck = nativeBinding.OnNeck
module.exports.OpeningMarubozu = nativeBinding.OpeningMarubozu
module.exports.OpeningRange = nativeBinding.OpeningRange
module.exports.OpenInterestDelta = nativeBinding.OpenInterestDelta
module.exports.OpenInterestMomentum = nativeBinding.OpenInterestMomentum
module.exports.OrderBookImbalanceFull = nativeBinding.OrderBookImbalanceFull
module.exports.OrderBookImbalanceTop1 = nativeBinding.OrderBookImbalanceTop1
module.exports.OrderBookImbalanceTopN = nativeBinding.OrderBookImbalanceTopN
module.exports.OrderFlowImbalance = nativeBinding.OrderFlowImbalance
module.exports.OuHalfLife = nativeBinding.OuHalfLife
module.exports.OvernightGap = nativeBinding.OvernightGap
module.exports.OvernightIntradayReturn = nativeBinding.OvernightIntradayReturn
module.exports.PainIndex = nativeBinding.PainIndex
module.exports.PairSpreadZScore = nativeBinding.PairSpreadZScore
module.exports.PairwiseBeta = nativeBinding.PairwiseBeta
module.exports.ParkinsonVolatility = nativeBinding.ParkinsonVolatility
module.exports.PearsonCorrelation = nativeBinding.PearsonCorrelation
module.exports.PercentAboveMa = nativeBinding.PercentAboveMa
module.exports.PercentageTrailingStop = nativeBinding.PercentageTrailingStop
module.exports.PercentB = nativeBinding.PercentB
module.exports.PerpetualPremiumIndex = nativeBinding.PerpetualPremiumIndex
module.exports.PGO = nativeBinding.PGO
module.exports.PiercingDarkCloud = nativeBinding.PiercingDarkCloud
module.exports.Pin = nativeBinding.Pin
module.exports.PivotReversal = nativeBinding.PivotReversal
module.exports.PLUS_DI = nativeBinding.PLUS_DI
module.exports.PLUS_DM = nativeBinding.PLUS_DM
module.exports.PMO = nativeBinding.PMO
module.exports.PointAndFigureBars = nativeBinding.PointAndFigureBars
module.exports.POLARIZED_FRACTAL_EFFICIENCY = nativeBinding.POLARIZED_FRACTAL_EFFICIENCY
module.exports.PPO = nativeBinding.PPO
module.exports.PpoHistogram = nativeBinding.PpoHistogram
module.exports.ProfileShape = nativeBinding.ProfileShape
module.exports.ProfitFactor = nativeBinding.ProfitFactor
module.exports.ProjectionBands = nativeBinding.ProjectionBands
module.exports.ProjectionOscillator = nativeBinding.ProjectionOscillator
module.exports.PSAR = nativeBinding.PSAR
module.exports.PVI = nativeBinding.PVI
module.exports.QQE = nativeBinding.QQE
module.exports.Qstick = nativeBinding.Qstick
module.exports.QuartileBands = nativeBinding.QuartileBands
module.exports.QuotedSpread = nativeBinding.QuotedSpread
module.exports.RangeBars = nativeBinding.RangeBars
module.exports.RealizedSpread = nativeBinding.RealizedSpread
module.exports.RealizedVolatility = nativeBinding.RealizedVolatility
module.exports.RecoveryFactor = nativeBinding.RecoveryFactor
module.exports.RectangleRange = nativeBinding.RectangleRange
module.exports.REFLEX = nativeBinding.REFLEX
module.exports.RegimeLabel = nativeBinding.RegimeLabel
module.exports.RelativeStrengthAB = nativeBinding.RelativeStrengthAB
module.exports.RenkoBars = nativeBinding.RenkoBars
module.exports.RenkoTrailingStop = nativeBinding.RenkoTrailingStop
module.exports.Resampler = nativeBinding.Resampler
module.exports.RickshawMan = nativeBinding.RickshawMan
module.exports.RisingThreeMethods = nativeBinding.RisingThreeMethods
module.exports.RMI = nativeBinding.RMI
module.exports.ROC = nativeBinding.ROC
module.exports.ROCP = nativeBinding.ROCP
module.exports.ROCR = nativeBinding.ROCR
module.exports.ROCR100 = nativeBinding.ROCR100
module.exports.RogersSatchellVolatility = nativeBinding.RogersSatchellVolatility
module.exports.RollingCorrelation = nativeBinding.RollingCorrelation
module.exports.RollingCovariance = nativeBinding.RollingCovariance
module.exports.RollingIqr = nativeBinding.RollingIqr
module.exports.ROLLINGMINMAX = nativeBinding.ROLLINGMINMAX
module.exports.RollingPercentileRank = nativeBinding.RollingPercentileRank
module.exports.RollingQuantile = nativeBinding.RollingQuantile
module.exports.RollingVWAP = nativeBinding.RollingVWAP
module.exports.RollMeasure = nativeBinding.RollMeasure
module.exports.RoofingFilter = nativeBinding.RoofingFilter
module.exports.RSI = nativeBinding.RSI
module.exports.RSquared = nativeBinding.RSquared
module.exports.RSX = nativeBinding.RSX
module.exports.RunBars = nativeBinding.RunBars
module.exports.RVI = nativeBinding.RVI
module.exports.RVIVolatility = nativeBinding.RVIVolatility
module.exports.RWI = nativeBinding.RWI
module.exports.SAMPLEENT = nativeBinding.SAMPLEENT
module.exports.SAREXT = nativeBinding.SAREXT
module.exports.SeasonalZScore = nativeBinding.SeasonalZScore
module.exports.SeparatingLines = nativeBinding.SeparatingLines
module.exports.SessionHighLow = nativeBinding.SessionHighLow
module.exports.SessionRange = nativeBinding.SessionRange
module.exports.SessionVwap = nativeBinding.SessionVwap
module.exports.SHANNONENT = nativeBinding.SHANNONENT
module.exports.Shark = nativeBinding.Shark
module.exports.SharpeRatio = nativeBinding.SharpeRatio
module.exports.ShootingStar = nativeBinding.ShootingStar
module.exports.ShortLine = nativeBinding.ShortLine
module.exports.SignedVolume = nativeBinding.SignedVolume
module.exports.SineWave = nativeBinding.SineWave
module.exports.SinglePrints = nativeBinding.SinglePrints
module.exports.Skewness = nativeBinding.Skewness
module.exports.SMA = nativeBinding.SMA
module.exports.SMI = nativeBinding.SMI
module.exports.SMMA = nativeBinding.SMMA
module.exports.SmoothedHeikinAshi = nativeBinding.SmoothedHeikinAshi
module.exports.SortinoRatio = nativeBinding.SortinoRatio
module.exports.SpearmanCorrelation = nativeBinding.SpearmanCorrelation
module.exports.SpinningTop = nativeBinding.SpinningTop
module.exports.SpreadAr1Coefficient = nativeBinding.SpreadAr1Coefficient
module.exports.SpreadBollingerBands = nativeBinding.SpreadBollingerBands
module.exports.SpreadHurst = nativeBinding.SpreadHurst
module.exports.StalledPattern = nativeBinding.StalledPattern
module.exports.StandardError = nativeBinding.StandardError
module.exports.StandardErrorBands = nativeBinding.StandardErrorBands
module.exports.StarcBands = nativeBinding.StarcBands
module.exports.STC = nativeBinding.STC
module.exports.StdDev = nativeBinding.StdDev
module.exports.StepTrailingStop = nativeBinding.StepTrailingStop
module.exports.SterlingRatio = nativeBinding.SterlingRatio
module.exports.StickSandwich = nativeBinding.StickSandwich
module.exports.Stochastic = nativeBinding.Stochastic
module.exports.StochasticCCI = nativeBinding.StochasticCCI
module.exports.StochRSI = nativeBinding.StochRSI
module.exports.SuperSmoother = nativeBinding.SuperSmoother
module.exports.SuperTrend = nativeBinding.SuperTrend
module.exports.SWMA = nativeBinding.SWMA
module.exports.T3 = nativeBinding.T3
module.exports.TailRatio = nativeBinding.TailRatio
module.exports.TakerBuySellRatio = nativeBinding.TakerBuySellRatio
module.exports.Takuri = nativeBinding.Takuri
module.exports.TasukiGap = nativeBinding.TasukiGap
module.exports.TDCamouflage = nativeBinding.TDCamouflage
module.exports.TDClop = nativeBinding.TDClop
module.exports.TDClopwin = nativeBinding.TDClopwin
module.exports.TDCombo = nativeBinding.TDCombo
module.exports.TDCountdown = nativeBinding.TDCountdown
module.exports.TDDeMarker = nativeBinding.TDDeMarker
module.exports.TDDifferential = nativeBinding.TDDifferential
module.exports.TDDWave = nativeBinding.TDDWave
module.exports.TDLines = nativeBinding.TDLines
module.exports.TDMovingAverage = nativeBinding.TDMovingAverage
module.exports.TDOpen = nativeBinding.TDOpen
module.exports.TDPressure = nativeBinding.TDPressure
module.exports.TDPropulsion = nativeBinding.TDPropulsion
module.exports.TDRangeProjection = nativeBinding.TDRangeProjection
module.exports.TDREI = nativeBinding.TDREI
module.exports.TDRiskLevel = nativeBinding.TDRiskLevel
module.exports.TDSequential = nativeBinding.TDSequential
module.exports.TDSetup = nativeBinding.TDSetup
module.exports.TDTrap = nativeBinding.TDTrap
module.exports.TEMA = nativeBinding.TEMA
module.exports.TermStructureBasis = nativeBinding.TermStructureBasis
module.exports.ThreeDrives = nativeBinding.ThreeDrives
module.exports.ThreeInside = nativeBinding.ThreeInside
module.exports.ThreeLineBreak = nativeBinding.ThreeLineBreak
module.exports.ThreeLineBreakBars = nativeBinding.ThreeLineBreakBars
module.exports.ThreeLineStrike = nativeBinding.ThreeLineStrike
module.exports.ThreeOutside = nativeBinding.ThreeOutside
module.exports.ThreeSoldiersOrCrows = nativeBinding.ThreeSoldiersOrCrows
module.exports.ThreeStarsInSouth = nativeBinding.ThreeStarsInSouth
module.exports.Thrusting = nativeBinding.Thrusting
module.exports.TickAggregator = nativeBinding.TickAggregator
module.exports.TickBars = nativeBinding.TickBars
module.exports.TickIndex = nativeBinding.TickIndex
module.exports.TII = nativeBinding.TII
module.exports.TimeBasedStop = nativeBinding.TimeBasedStop
module.exports.TimeOfDayReturnProfile = nativeBinding.TimeOfDayReturnProfile
module.exports.TowerTopBottom = nativeBinding.TowerTopBottom
module.exports.TpoProfile = nativeBinding.TpoProfile
module.exports.TradeImbalance = nativeBinding.TradeImbalance
module.exports.TradeSignAutocorrelation = nativeBinding.TradeSignAutocorrelation
module.exports.TradeVolumeIndex = nativeBinding.TradeVolumeIndex
module.exports.TREND_STRENGTH_INDEX = nativeBinding.TREND_STRENGTH_INDEX
module.exports.TRENDFLEX = nativeBinding.TRENDFLEX
module.exports.TrendLabel = nativeBinding.TrendLabel
module.exports.TreynorRatio = nativeBinding.TreynorRatio
module.exports.Triangle = nativeBinding.Triangle
module.exports.TRIMA = nativeBinding.TRIMA
module.exports.Trin = nativeBinding.Trin
module.exports.TripleTopBottom = nativeBinding.TripleTopBottom
module.exports.Tristar = nativeBinding.Tristar
module.exports.TRIX = nativeBinding.TRIX
module.exports.TrueRange = nativeBinding.TrueRange
module.exports.TSF = nativeBinding.TSF
module.exports.TsfOscillator = nativeBinding.TsfOscillator
module.exports.TSI = nativeBinding.TSI
module.exports.TSV = nativeBinding.TSV
module.exports.TTM_TREND = nativeBinding.TTM_TREND
module.exports.TtmSqueeze = nativeBinding.TtmSqueeze
module.exports.TurnOfMonth = nativeBinding.TurnOfMonth
module.exports.Tweezer = nativeBinding.Tweezer
module.exports.TwiggsMoneyFlow = nativeBinding.TwiggsMoneyFlow
module.exports.TwoCrows = nativeBinding.TwoCrows
module.exports.TypicalPrice = nativeBinding.TypicalPrice
module.exports.UlcerIndex = nativeBinding.UlcerIndex
module.exports.UltimateOscillator = nativeBinding.UltimateOscillator
module.exports.UniqueThreeRiver = nativeBinding.UniqueThreeRiver
module.exports.UNIVERSALOSC = nativeBinding.UNIVERSALOSC
module.exports.UpDownVolumeRatio = nativeBinding.UpDownVolumeRatio
module.exports.UpsideGapThreeMethods = nativeBinding.UpsideGapThreeMethods
module.exports.UpsideGapTwoCrows = nativeBinding.UpsideGapTwoCrows
module.exports.UpsidePotentialRatio = nativeBinding.UpsidePotentialRatio
module.exports.ValueArea = nativeBinding.ValueArea
module.exports.ValueAtRisk = nativeBinding.ValueAtRisk
module.exports.Variance = nativeBinding.Variance
module.exports.VarianceRatio = nativeBinding.VarianceRatio
module.exports.VerticalHorizontalFilter = nativeBinding.VerticalHorizontalFilter
module.exports.VIDYA = nativeBinding.VIDYA
module.exports.VolatilityCone = nativeBinding.VolatilityCone
module.exports.VolatilityOfVolatility = nativeBinding.VolatilityOfVolatility
module.exports.VolatilityRatio = nativeBinding.VolatilityRatio
module.exports.VoltyStop = nativeBinding.VoltyStop
module.exports.VolumeBars = nativeBinding.VolumeBars
module.exports.VolumeByTimeProfile = nativeBinding.VolumeByTimeProfile
module.exports.VolumeOscillator = nativeBinding.VolumeOscillator
module.exports.VolumePriceTrend = nativeBinding.VolumePriceTrend
module.exports.VolumeProfile = nativeBinding.VolumeProfile
module.exports.VolumeRsi = nativeBinding.VolumeRsi
module.exports.VolumeWeightedMacd = nativeBinding.VolumeWeightedMacd
module.exports.VolumeWeightedSr = nativeBinding.VolumeWeightedSr
module.exports.Vortex = nativeBinding.Vortex
module.exports.Vpin = nativeBinding.Vpin
module.exports.VWAP = nativeBinding.VWAP
module.exports.VwapStdDevBands = nativeBinding.VwapStdDevBands
module.exports.VWMA = nativeBinding.VWMA
module.exports.VZO = nativeBinding.VZO
module.exports.Wad = nativeBinding.Wad
module.exports.WAVE_PM = nativeBinding.WAVE_PM
module.exports.WaveTrend = nativeBinding.WaveTrend
module.exports.Wedge = nativeBinding.Wedge
module.exports.WeightedClose = nativeBinding.WeightedClose
module.exports.WickRatio = nativeBinding.WickRatio
module.exports.WilliamsFractals = nativeBinding.WilliamsFractals
module.exports.WilliamsR = nativeBinding.WilliamsR
module.exports.WinRate = nativeBinding.WinRate
module.exports.WMA = nativeBinding.WMA
module.exports.WoodiePivots = nativeBinding.WoodiePivots
module.exports.YangZhangVolatility = nativeBinding.YangZhangVolatility
module.exports.YoyoExit = nativeBinding.YoyoExit
module.exports.ZeroLagMACD = nativeBinding.ZeroLagMACD
module.exports.ZigZag = nativeBinding.ZigZag
module.exports.ZLEMA = nativeBinding.ZLEMA
module.exports.ZScore = nativeBinding.ZScore
module.exports.fetchBinanceKlines = nativeBinding.fetchBinanceKlines
module.exports.version = nativeBinding.version
