"""Assert that every place carrying the release version agrees.

The version lives in twenty-odd files across six package managers, and a bump
that misses one produces a release where, say, the npm package pins a native
binary that was never published. That failure surfaces at install time, on a
user's machine, after the tag is irreversible -- so it is worth a cheap check
before the tag rather than a patch release after it.

    python scripts/check_version_sync.py                # all files agree
    python scripts/check_version_sync.py --previous 1.0.3   # and none is stale

The file list is explicit rather than a repository-wide grep on purpose:
`Cargo.lock` records third-party crates that will occasionally sit at the same
version as this project, and a grep that matched those would either be noisy or
be silenced with exceptions that outlive their reason.

Counts are exact, not "at least one". A pattern that should match six platform
dependencies and finds five has found the bug this file exists for.
"""

from __future__ import annotations

import argparse
import os
import re
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

# (path, description, pattern with @V@ standing in for the version, expected count)
TOUCHPOINTS: list[tuple[str, str, str, int]] = [
    ("Cargo.toml", "workspace version", r'(?m)^version = "@V@"$', 1),
    (
        "Cargo.toml",
        "workspace dependency pins",
        r'path = "crates/wickra-[a-z]+", version = "@V@"',
        # wickra-simd, wickra-core, wickra-data: every published crate another
        # workspace member depends on.
        3,
    ),
    # wickra-data pins wickra-core by path AND version, so a bump that misses it
    # publishes a data crate depending on a core version that does not exist.
    (
        "crates/wickra-data/Cargo.toml",
        "wickra-core path dependency",
        r'version = "@V@"',
        1,
    ),
    ("bindings/python/pyproject.toml", "wheel version", r'(?m)^version = "@V@"$', 1),
    ("bindings/node/package.json", "package version", r'"version": "@V@"', 1),
    (
        "bindings/node/package.json",
        "optional platform dependencies",
        r'"wickra-[a-z0-9-]+": "@V@"',
        6,
    ),
    ("bindings/r/DESCRIPTION", "R package version", r"(?m)^Version: @V@$", 1),
    ("bindings/java/pom.xml", "Maven version", r"<version>@V@</version>", 1),
    (
        "bindings/csharp/Wickra/Wickra.csproj",
        "NuGet version",
        r"<Version>@V@</Version>",
        1,
    ),
    # The benchmarks pom depends on the published binding rather than on the
    # sibling module, and was found stale at 0.9.6 while 1.0.0 was being cut.
    (
        "bindings/java/benchmarks/pom.xml",
        "wickra dependency",
        r"<version>@V@</version>",
        1,
    ),
    # The example depends on the published binding, so it carries the version
    # twice: its own, and the dependency it resolves.
    ("examples/java/pom.xml", "example version and dependency", r"<version>@V@</version>", 2),
    # Maven snippet and Gradle snippet, both copied by readers verbatim.
    ("bindings/java/README.md", "install snippets", r"@V@", 2),
    # Prose sentence, the supported row, and the unsupported bound.
    ("SECURITY.md", "supported version", r"@V@", 3),
    # The citation names the release it belongs to. The bump moves the
    # `date-released` beside it, so a stale `version` here is not merely absent
    # -- the two lines disagree, and GitHub's citation box and Zenodo both read
    # them. Nothing else in CI touches this file.
    ("CITATION.cff", "citation version", r'(?m)^version: "@V@"$', 1),
    # npm records the package's own version twice in the lockfile: once at the
    # top level and once in the `packages[""]` entry. Only the first is what
    # `npm version` rewrites, so the second goes stale on its own -- it sat at
    # 1.0.1 across two releases and was repaired by an unrelated Dependabot
    # regeneration (#426) rather than by anything watching. Both are ours and
    # both are checked exactly; the rest of the lockfile stays a presence check
    # in GENERATED, because those versions belong to other people.
    (
        "bindings/node/package-lock.json",
        "own version, both records",
        r'"name": "wickra",\s+"version": "@V@"',
        2,
    ),
]

# Each platform package declares its own version.
PLATFORMS = [
    "darwin-arm64",
    "darwin-x64",
    "linux-arm64-gnu",
    "linux-x64-gnu",
    "win32-arm64-msvc",
    "win32-x64-msvc",
]
for platform in PLATFORMS:
    TOUCHPOINTS.append(
        (
            f"bindings/node/npm/{platform}/package.json",
            "platform package version",
            r'"version": "@V@"',
            1,
        )
    )

# Generated files: regenerated by their own toolchain, checked here so a bump that
# forgot to rebuild them is caught before the tag rather than at install. Only
# presence is asserted, not a count -- the count is the generator's business and
# changes when the generator does, which would make an exact number a false alarm
# waiting to happen. index.js earns its place: it shipped 0.9.7 inside the v0.9.9
# tag, because napi only rewrites it when somebody rebuilds.
GENERATED = [
    ("bindings/node/index.js", "napi version guard", r"'@V@'"),
    ("bindings/node/package-lock.json", "lockfile", r'"version": "@V@"'),
    ("examples/node/package-lock.json", "example lockfile", r'"version": "@V@"'),
]


def read(rel: str) -> str | None:
    path = os.path.join(ROOT, rel)
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as handle:
        return handle.read()


def workspace_version() -> str:
    text = read("Cargo.toml")
    if text is None:
        raise SystemExit("Cargo.toml not found; run this from the repository")
    match = re.search(r'(?m)^version = "([^"]+)"$', text)
    if match is None:
        raise SystemExit("Cargo.toml declares no workspace version")
    return match.group(1)


def check(version: str, previous: str | None) -> int:
    failures: list[str] = []
    checked = 0

    for rel, what, pattern, expected in TOUCHPOINTS:
        text = read(rel)
        if text is None:
            failures.append(f"{rel}: missing, but listed as carrying the version")
            continue
        found = len(re.findall(pattern.replace("@V@", re.escape(version)), text))
        checked += 1
        if found != expected:
            failures.append(
                f"{rel}: {what} -- expected {expected} occurrence(s) of {version}, found {found}"
            )

    for rel, what, pattern in GENERATED:
        text = read(rel)
        if text is None:
            failures.append(f"{rel}: missing, but listed as carrying the version")
            continue
        checked += 1
        if not re.search(pattern.replace("@V@", re.escape(version)), text):
            failures.append(f"{rel}: {what} -- no occurrence of {version}; regenerate it")

    # A stale copy of the previous version is the other half of the same mistake:
    # every file agreeing is not enough if one of them agrees on the old number.
    if previous is not None and previous != version:
        stale = []
        stale_sources = [(rel, pat) for rel, _, pat, _ in TOUCHPOINTS]
        stale_sources += [(rel, pat) for rel, _, pat in GENERATED]
        for rel, pattern in stale_sources:
            text = read(rel)
            if text is None:
                continue
            if re.search(pattern.replace("@V@", re.escape(previous)), text):
                stale.append(rel)
        # Cargo.lock names this project's own crates; third-party entries that
        # happen to share the version are none of our business.
        lock = read("Cargo.lock")
        if lock is not None:
            for block in lock.split("[[package]]"):
                if re.search(r'(?m)^name = "wickra', block) and re.search(
                    rf'(?m)^version = "{re.escape(previous)}"$', block
                ):
                    stale.append("Cargo.lock")
                    break
        for rel in sorted(set(stale)):
            failures.append(f"{rel}: still carries the previous version {previous}")

    print(f"version {version}: checked {checked} declarations")
    if failures:
        print("\nversion declarations disagree:", file=sys.stderr)
        for line in failures:
            print(f"  {line}", file=sys.stderr)
        return 1
    print("every declaration agrees.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--previous",
        help="also assert no declaration still carries this earlier version",
    )
    args = parser.parse_args()
    return check(workspace_version(), args.previous)


if __name__ == "__main__":
    raise SystemExit(main())
